
//import static documents.filename;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HCS
 */
public class dashbord extends javax.swing.JFrame {

    /**
     * Creates new form dashbord
     */
    public dashbord() {
        initComponents();
        aname.setText(applicant.aname);
        acnic.setText(applicant.acnic);
        areligion.setText(applicant.areligion);
        acity.setText(applicant.acity);
        agender.setText(applicant.agender);
        aaddres.setText(applicant.aaddress);
       aphone.setText(applicant.aphone);
        gname.setText(guardain.ganame);
        gcnic.setText(guardain.gcnic);
        gphone.setText(guardain.gphone);
        gjob.setText(guardain.gjob);
        grelation.setText(guardain.grelation);
        mnum.setText(academic.mnumber);
        mpass.setText(academic.mpassyear);
        mgrade.setText(academic.mgrade);
        mboard.setText(academic.mboard);
        inum.setText(academic.inumber);
        igrade.setText(academic.igrade);
        ipass.setText(academic.ipassyear);
        iboard.setText(academic.iboard);
        f1.setText(academic.f1);
        f2.setText(academic.f2);
        f3.setText(academic.f2);
        System.out.println(documents.filename);
       imgicon.setIcon(new ImageIcon(documents.filename));
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        c = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel24 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        aname = new javax.swing.JLabel();
        acnic = new javax.swing.JLabel();
        aphone = new javax.swing.JLabel();
        agender = new javax.swing.JLabel();
        aaddres = new javax.swing.JLabel();
        areligion = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        acity = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        gjob = new javax.swing.JLabel();
        gphone = new javax.swing.JLabel();
        gcnic = new javax.swing.JLabel();
        gname = new javax.swing.JLabel();
        f1 = new javax.swing.JLabel();
        f3 = new javax.swing.JLabel();
        mpass = new javax.swing.JLabel();
        ipass = new javax.swing.JLabel();
        mgrade = new javax.swing.JLabel();
        mnum = new javax.swing.JLabel();
        inum = new javax.swing.JLabel();
        igrade = new javax.swing.JLabel();
        f2 = new javax.swing.JLabel();
        mboard = new javax.swing.JLabel();
        iboard = new javax.swing.JLabel();
        grelation = new javax.swing.JLabel();
        imgicon = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel2.setText("              ADMISON FORM REVIEW");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 520, 40));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("APPLICANT NAME");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 110, -1));

        jLabel4.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        jLabel4.setText("APPLICANT PHONE NUMBER");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        jLabel5.setText(" APPLICANT CNIC");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 120, 20));

        jLabel6.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        jLabel6.setText("APPLICANT GENDER");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 170, -1));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel7.setText("GURDAIN OR PARENTS INFORMATION");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 390, 30));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 50, -1));

        jLabel9.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        jLabel9.setText("GURDAIN NAME");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 100, 20));

        jLabel10.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        jLabel10.setText("GURDIAN CNIC");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 100, 20));

        jLabel11.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        jLabel11.setText("RELATION WITH APPLICANT");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 190, 20));

        c.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        c.setText("GURDAIN PHONE NUMBER");
        getContentPane().add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 160, 20));

        jLabel13.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel13.setText("APPLICANT ACADEMIC INFORMATION");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 390, 40));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel14.setText("MATRIC NUMBER");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel15.setText("MATRIC GRADE");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, -1, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel16.setText("MATRIC PASSING YEAR");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, -1, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel17.setText("INTER NUMBER");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 100, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel18.setText("INTER GRADE");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 100, -1));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel19.setText("INTER PASSING YEARS");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, 160, 20));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel20.setText("MATRIC BOARD");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 110, 20));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel21.setText("INTER BOARD");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 480, 100, 20));

        jLabel22.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        jLabel22.setText("APPLICANT RELIGON");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, -1, 20));

        jLabel23.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        jLabel23.setText("APPLICANT ADDRESS");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 160, -1));

        jLabel25.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel25.setText("YOUR 3 DESIRE FIELD FOR ADMISION");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, 440, 20));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel26.setText("FIELD 1");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 590, 80, 20));

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel27.setText("FIELD 2");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 590, -1, 20));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel28.setText("FIELD 3");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 590, -1, 20));
        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, -1, -1));
        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, -1, -1));

        jLabel24.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel24.setText("APPLICANT PERSONAL INFORMATION");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 430, 30));

        submit.setBackground(new java.awt.Color(0, 153, 0));
        submit.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 670, 150, -1));

        aname.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        aname.setText("jLabel31");
        getContentPane().add(aname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 130, 20));

        acnic.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        acnic.setText("jLabel30");
        getContentPane().add(acnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 130, 20));

        aphone.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        aphone.setText("jLabel33");
        getContentPane().add(aphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 130, -1));

        agender.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        agender.setText("jLabel34");
        getContentPane().add(agender, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 90, -1));

        aaddres.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        aaddres.setText("jLabel32");
        getContentPane().add(aaddres, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 80, 130, -1));

        areligion.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        areligion.setText("jLabel35");
        getContentPane().add(areligion, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 110, 120, 20));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 100, -1));

        jLabel36.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel36.setText("APPLICANT CITY");
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 100, -1));

        acity.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        acity.setText("jLabel37");
        getContentPane().add(acity, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 150, -1));

        jLabel38.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel38.setText("GUARDAIN JOB STATUS");
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, -1, -1));

        gjob.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        gjob.setText("jLabel39");
        getContentPane().add(gjob, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 45, 230, 220));

        gphone.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        gphone.setText("jLabel40");
        getContentPane().add(gphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 140, 20));

        gcnic.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        gcnic.setText("jLabel43");
        getContentPane().add(gcnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 120, 20));

        gname.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        gname.setText("jLabel43");
        getContentPane().add(gname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 120, 20));

        f1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        f1.setText("jLabel45");
        getContentPane().add(f1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 590, 100, 20));

        f3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        f3.setText("jLabel46");
        getContentPane().add(f3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 580, 150, 30));

        mpass.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        mpass.setText("jLabel46");
        getContentPane().add(mpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 350, 150, 30));

        ipass.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ipass.setText("jLabel46");
        getContentPane().add(ipass, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 400, 150, 30));

        mgrade.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        mgrade.setText("jLabel46");
        getContentPane().add(mgrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 150, 30));

        mnum.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        mnum.setText("jLabel45");
        getContentPane().add(mnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 100, 20));

        inum.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        inum.setText("jLabel45");
        getContentPane().add(inum, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 100, 20));

        igrade.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        igrade.setText("jLabel46");
        getContentPane().add(igrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 150, 30));

        f2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        f2.setText("jLabel45");
        getContentPane().add(f2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 590, 100, 20));

        mboard.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        mboard.setText("jLabel45");
        getContentPane().add(mboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 490, 100, 20));

        iboard.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        iboard.setText("jLabel46");
        getContentPane().add(iboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 470, 150, 30));

        grelation.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        grelation.setText("jLabel40");
        getContentPane().add(grelation, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 140, 20));
        getContentPane().add(imgicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 20, 320, 240));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 153, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("PRINT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 670, -1, -1));

        setSize(new java.awt.Dimension(1614, 866));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        
       dbfile d=new dbfile();
       d.formdata(applicant.aname, applicant.acnic, applicant.areligion, applicant.aphone, applicant.acity, applicant.agender, applicant.aaddress, guardain.ganame,guardain.gcnic, guardain.gphone, guardain.gjob, guardain.grelation, academic.mnumber,academic.mgrade ,academic.mboard, academic.mpassyear, academic.inumber, academic.igrade, academic.ipassyear, academic.iboard, academic.f1, academic.f2, academic.f3);
       
       studentformdetail s=new studentformdetail();
       s.setVisible(true);
       dispose();
    }//GEN-LAST:event_submitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName("Print Data");
            
            job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                    pf.setOrientation(PageFormat.LANDSCAPE);
                 if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47,0.47);
                
             ///  panelp.print(g2);
         
               
                return Printable.PAGE_EXISTS;
                         
                
            }
    });
            boolean ok = job.printDialog();
        if(ok){
        try{
            
        job.print();
        }
        catch (PrinterException ex){
	ex.printStackTrace();
}
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashbord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aaddres;
    private javax.swing.JLabel acity;
    private javax.swing.JLabel acnic;
    private javax.swing.JLabel agender;
    private javax.swing.JLabel aname;
    private javax.swing.JLabel aphone;
    private javax.swing.JLabel areligion;
    private javax.swing.JLabel c;
    private javax.swing.JLabel f1;
    private javax.swing.JLabel f2;
    private javax.swing.JLabel f3;
    private javax.swing.JLabel gcnic;
    private javax.swing.JLabel gjob;
    private javax.swing.JLabel gname;
    private javax.swing.JLabel gphone;
    private javax.swing.JLabel grelation;
    private javax.swing.JLabel iboard;
    private javax.swing.JLabel igrade;
    private javax.swing.JLabel imgicon;
    private javax.swing.JLabel inum;
    private javax.swing.JLabel ipass;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel mboard;
    private javax.swing.JLabel mgrade;
    private javax.swing.JLabel mnum;
    private javax.swing.JLabel mpass;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
